### ISSUE TITLE
Duplicate value 'attr/background'

### ISSUE THREAD

**Issue by lorensoftware** [TerryJung/SwipeAnimationButton#1]
I get this error: "Duplicate value for resource 'attr/background' with config ' ' "

**Comment by TerryJung** [comment]
Hi. thanks to use this project.

could you give me detail of your Logs?

**Comment by lorensoftware** [comment]
C:\Users\lorenzor\.gradle\caches\transforms-2\files-2.1\15508629dd32844505caa6e6c90e0dc1\jetified-SwipeAnimationButton-0.1.0\res\values\values.xml:4:5-13:25: AAPT: error: duplicate value for resource 'attr/background' with config ''.

**Comment by VinitSainiKs** [comment]
I am also getting the same error. I can resolve this if you allow me to .

**Comment by TerryJung** [comment]
> I am also getting the same error. I can resolve this if you allow me to .

@VinitSainiKs yes. why not? nowadays i can't care about this issue. because i am busy on my job. could you contribute it ?

**Comment by codeaskush** [comment]
> I am also getting the same error. I can resolve this if you allow me to .

Any updates on its fixes?
Would mean a lot if it did

Edit : **SOLVED**

-  Open the _attrs.xml_
-  Find the _attrs name = "background"_
-  Change the name `background` to something else (`backgroundSwipe` maybe, or anything you like)
-  Change the same field in Java code ( You'll get the hint where to change after you change the xml attrs)
- Run it!

Maybe the keyword 'background' was not permitted in the xml so maybe that error persists.

**Comment by TerryJung** [comment]
Can i close this?

**Comment by codeaskush** [comment]
> Can i close this?

Yes please :)
